# Generated by Django 3.1.7 on 2021-04-14 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0002_studentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 13, 33, 11, 919379)),
        ),
    ]
