# Generated by Django 3.1.7 on 2021-04-16 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0003_studentrecord_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='Issuedate',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='author',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='bookName',
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='rollNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Issuedate', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 55, 25, 418795))),
                ('BookStatus', models.CharField(default='False', max_length=10)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='need.studentrecord')),
            ],
        ),
    ]
