# Generated by Django 3.1.7 on 2021-04-21 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0005_auto_20210416_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 15, 20, 27, 477372)),
        ),
    ]
