# Generated by Django 3.1.7 on 2021-05-09 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0007_auto_20210421_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 14, 8, 56, 244024)),
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Issuedate', models.DateTimeField()),
                ('DueDate', models.DateTimeField()),
                ('BookStatus', models.CharField(default='True', max_length=10)),
                ('Fine', models.IntegerField(default=0)),
                ('Comment', models.CharField(default='All Good', max_length=200)),
                ('IdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='need.studentrecord')),
            ],
        ),
    ]
