# Generated by Django 3.1.7 on 2021-05-09 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0008_auto_20210509_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 18, 12, 36, 785402)),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 18, 12, 36, 784401)),
        ),
    ]
