# Generated by Django 3.1.7 on 2021-03-01 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20210301_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 7, 42, 55, 950522, tzinfo=utc)),
        ),
    ]
