# Generated by Django 3.1.7 on 2021-03-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
